### ISSUE TITLE
Question about data preprocess

### ISSUE THREAD

**Issue by yangzhao1230** [kingstdio/ECRECer#1]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/kingstdio/ECRECer/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

Thanks for your great work and ncie code!

In 'prepare_task_dataset.ipynb', it seems there is a bug in the following code:
'''
# !pip install fair-esm
from tools import embedding_esm as esmebd
if len(needesm)>0:
    tr_rep0, tr_rep32, tr_rep33 = esmebd.get_rep_multi_sequence(sequences=needesm, model='esm1b_t33_650M_UR50S',seqthres=1022)

    #merge existing
    feature_esm0 = pd.concat([feature_esm0, tr_rep0], axis=0).reset_index(drop=True)
    feature_esm32 = pd.concat([feature_esm32, tr_rep32], axis=0).reset_index(drop=True)
    feature_esm33 = pd.concat([feature_esm33, tr_rep33], axis=0).reset_index(drop=True)

    #save
    feature_esm0.to_feather(cfg.FILE_FEATURE_ESM0)
    feature_esm32.to_feather(cfg.FILE_FEATURE_ESM32)
    feature_esm33.to_feather(cfg.FILE_FEATURE_ESM33)
'''
Note that feature_esm0 has not been declared (If there is no existing features when I run the code for the first time), so I get a error as follow:
![image](https://github.com/kingstdio/ECRECer/assets/52462696/0177b4f0-3af0-424a-96b4-4e5319c2b3d2)

### 期望的现象 / What you expected

See  What happened'

### 如何重现此问题 / How to reproduce

See  What happened'

### 操作系统版本 / OS version

See  What happened'

### 浏览器或客户端版本 / Browser/client version

See  What happened'

**Comment by kingstdio** [comment]
Thank you for your interest in our work.

We apologize for the inconvenience caused. The issue you encountered is primarily due to the incompatibility between the defined ROOTDIR in the config.py file and your workspace. To resolve this, please manually specify the absolute project DIR that corresponds to your workspace.

<img width="476" alt="image" src="https://github.com/kingstdio/ECRECer/assets/7359557/41723336-efd7-4c4f-8e61-d6d0d25630ac">


Please note that we will leave this issue open for your feedback.

**Comment by yangzhao1230** [comment]
First of all, thank you for your quick and detailed reply, and I apologize for not noticing the GitHub issue response email earlier. 

Secondly, regarding this issue, I have now realized that you have provided the processed data, and I am currently downloading the processed data. 

As for the problem mentioned in the issue, I am still confused. I believe the issue I encountered is not related to ROOTDIR. Even after following your advice and modifying ROOTDIR to an absolute path, I encountered the same problem. Below, I will elaborate on my confusion in detail:
The error I encountered is that "feature_esm0" is not declared at this location：
`feature_esm0 = pd.concat([feature_esm0, tr_rep0], axis=0).reset_index(drop=True)`,  and the only possible place where "feature_esm0" could have been defined is `if ftool.isfileExists(cfg.FILE_FEATURE_ESM0):
    feature_esm0 = pd.read_feather(cfg.FILE_FEATURE_ESM0)
    feature_esm32 = pd.read_feather(cfg.FILE_FEATURE_ESM32)
    feature_esm33 = pd.read_feather(cfg.FILE_FEATURE_ESM33)
    feature_unirep = pd.read_feather(cfg.FILE_FEATURE_UNIREP)
    feature_onehot = pd.read_feather(cfg.FILE_FEATURE_ONEHOT)
    #caculate embedding list
    needesm = full_snap_data[~full_snap_data.id.isin(list(set(feature_esm33.id)))]
    needunirep = full_snap_data[~full_snap_data.id.isin(list(set(feature_unirep.id)))]
    needonehot = full_snap_data[~full_snap_data.id.isin(list(set(feature_onehot.id)))]`. However, it appears that when I first ran this code, the file cfg.FILE_FEATURE_ESM0 did not exist, which resulted in "feature_esm0" not being declared and caused the error I encountered. If cfg.FILE_FEATURE_ESM0 has been created in the previous code, I would greatly appreciate it if you could let me know the specific section of code where it was created.

**Comment by yangzhao1230** [comment]
One more question: when I ran task1.ipynb, an error occurred stating "No such file or directory: '/tmp/test_fasta_results.tsv'." In the repository you provided, the tmp directory is empty, and it appears that no code has been written to write any data to the tmp directory. I would greatly appreciate it if you could assist me in resolving this issue.

**Comment by kingstdio** [comment]
"I apologize for the delayed response; it was caused by an uninitialized variable. I have updated the code in the second code block of Section 7.1. If you have any additional questions, please address them in this issue."
<img width="1016" alt="image" src="https://github.com/kingstdio/ECRECer/assets/7359557/47638cd4-579a-4dba-88b0-339b8a0dde8a">
