### ISSUE TITLE
ModuleNotFoundError: No module named 'jax_unirep'

### ISSUE THREAD

**Issue by dsaeedeh** [kingstdio/ECRECer#3]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/kingstdio/ECRECer/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

Hi,

I received the following error while running the prepare_task_dataset.ipynb file.  

File "/ECRECer/tools/embedding_unirep.py", line 6, in <module>
    from jax_unirep import get_reps
ModuleNotFoundError: No module named 'jax_unirep'

I'd appreciate it if you could help me with this issue.

### 期望的现象 / What you expected

module jax_unirep is not defined

### 如何重现此问题 / How to reproduce

.

### 操作系统版本 / OS version

Ubuntu

### 浏览器或客户端版本 / Browser/client version

.

**Comment by dsaeedeh** [comment]
Hi,

I think benchmark_evaluation.py is not existed in the directory. Could you please let me know how I can get the file? Thanks.

**Comment by kingstdio** [comment]
Switch the code branch to 'main' for additional information; however, executing the code requires a higher level of coding expertise.
<img width="412" alt="image" src="https://github.com/kingstdio/ECRECer/assets/7359557/725849d1-d24a-4c39-81af-8246e0a6aa77">

**Comment by dsaeedeh** [comment]
Thank you for your response @kingstdio. I also noticed that prepare_slice_file and prepare_slice_file_onlyx functions in benchmark_common.py and train_ec_slice function in benchmark_train.py are not defined. Could you please also let me know where I can find functions?

**Comment by kingstdio** [comment]
Hello @davoudisaeedeh, 
After getting the benchmark dataset (using prepare_task_dataset.ipynb), please omit the section labeled 'Step-by-step benchmarking' in these notebooks as it contains outdated codes. I will be updating this part of the code at a later time. To quickly replicate the results, kindly refer to the 'High throughput benchmarking' section instead.

**Comment by cgx10957** [comment]
Hello,
I had the same problem, make_ec_label, train_ec_slice functions in benchmark_train.py and prepare_slice_file  function in benchmark_common.py  are not defined. Could you please also let me know where I can find functions? Or could you provide cfg.FILE_EC_LABEL_DICT data?

**Comment by cgxbio** [comment]
Hello,
I had the same problem, make_ec_label, train_ec_slice functions in benchmark_train.py and prepare_slice_file  function in benchmark_common.py  are not defined. Could you please also let me know where I can find functions? Or could you provide cfg.FILE_EC_LABEL_DICT data and model?

**Comment by kingstdio** [comment]
The functions 'make_ec_label' and 'train_ec_slice' are considered outdated components. For a quick overview of the pipelines, please refer to [production.py](https://github.com/kingstdio/ECRECer/blob/release/production.py). I intend to update the entire procedure soon.
