### ISSUE TITLE
conda env create -f env.yaml

### ISSUE THREAD

**Issue by Stevenleizheng** [kingstdio/ECRECer#4]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/kingstdio/ECRECer/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

I have downloaded your repository and run the command named "conda env create -f env.yaml". The error of 'Found conflicts! Looking for incompatible packages.' emerged for a while. How do I solve this problem? I don't find these conflicts.

### 期望的现象 / What you expected

*

### 如何重现此问题 / How to reproduce

conda env create -f env.yaml
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

### 操作系统版本 / OS version

LINUS

### 浏览器或客户端版本 / Browser/client version

None

**Comment by kingstdio** [comment]
Apologies for the delayed response. I'm unable to replicate the issue at the moment. Could you please furnish additional details for further assistance?
