### ISSUE TITLE
Please check your file

### ISSUE THREAD

**Issue by Joshcole2504** [kingstdio/ECRECer#5]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/kingstdio/ECRECer/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

I have been running some of the JGI mycocosm fungal genomes through the ECRECer web server. I have found after removing any '*' stop codon flags the server runs perfectly for all the genomes except from one. Whenever I try run this genome it returns a 'Please check your file' notification. I have screened this one genome the same as all others (11 other genomes) but can't get this one genome to run. 

### 期望的现象 / What you expected

ECRECer to run on the select genome. 

### 如何重现此问题 / How to reproduce

https://mycocosm.jgi.doe.gov/Rhice1_1/Rhice1_1.home.html > download > files > annotation > 'filtered models best' > functional annotations > proteins > Rhice1_1_GeneCatalog_proteins_20160727.aa.fasta.gz. Unzip, Remove the stop codons (tr -d '*' < Rhice1_1_GeneCatalog_proteins_20160727.aa.fasta) and save. Upload the file and it returns the 'Please check your file' error. Try with any other of the genomes, and it has worked for the rest. 

### 操作系统版本 / OS version

Sonoma 14.4.1 

### 浏览器或客户端版本 / Browser/client version

Chrome Version 124.0.6367.119

### 其他环境 / Other environments

Web Server used

**Comment by kingstdio** [comment]
Thanks for using ECRECer! We identified an issue with the program related to the characters '*' and 'x' within sequences. We've updated the program to handle these characters correctly. Please feel free to retest the program.
