### ISSUE TITLE
FIle Not Found Error

### ISSUE THREAD

**Issue by Phuangji** [kingstdio/ECRECer#6]
### 先决条件 / Prerequisites

- [X] 该问题未被其他 [issues](https://github.com/kingstdio/ECRECer/issues) 提出。
No previous issues have reported this problem.

### 发生了什么 / What happened

When i run the production.py, it says that ECRECER/data/uniprot/sprot_latest.feather file not found. I have downloaded every file in the README in data directory. I actually found the relevant download address in the config.py file, but the download address you gave is in dat format, not feather format as required. Maybe you need to update the readme file in data directory. Could please tell me where can I get the feather file I want?

### 期望的现象 / What you expected

-

### 如何重现此问题 / How to reproduce

-

### 操作系统版本 / OS version

Linux

### 浏览器或客户端版本 / Browser/client version

-

**Comment by kingstdio** [comment]
Dear Phuangji， 
Pls run the [prepare_production_data.ipynb](https://github.com/kingstdio/ECRECer/blob/release/prepare_production_data.ipynb) first to prepare production data. I will update readme later.

![image](https://github.com/kingstdio/ECRECer/assets/7359557/ea81755a-8666-4572-a297-527e8c2334a6)
